language: node_js

cache:
  yarn: true
  directories:
   - /home/travis/.rvm/

node_js:
  - 6
  - 8

services:
  - redis-server

before_install:
  - rvm install 2.5.0
  - gem install bundler -v 2.0.2
  - bundle install

script:
  - bundle exec rake spec
  - grunt spec

after_success:
  - bundle exec codeclimate-test-reporter
