language: node_js

cache:
  yarn: true
  directories:
   - /home/travis/.rvm/

node_js:
  - 8
  - 19.5

services:
  - redis-server

before_install:
  - rvm install 2.7.5
  - gem install bundler
  - bundle install

script:
  - bundle exec rake spec
  - grunt spec

after_success:
  - bundle exec codeclimate-test-reporter
